version: '3.3'
services:
  db:
    image: mysql:5.6.43
    restart: always
    environment:
      MYSQL_DATABASE: 'scootami'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: